trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Define Variables for Environments
variables:
  AzureServiceConnection: AV-Azure-ServiceConnection # Azure Service Connection Name
  
  TFStateResourceGroup: "RG-AVE"
  TFStateStorageAccount: ave
  TFStateStorageAccountContainer: terraformstate
  TFStateKey: aks.terraform.tfstate

  DevEnv: dev
  TestEnv: test

  SSHKeyFileName: "av-tf-aks-ssh-key.pub"


# Stage-1: Terraform Validate Stage
## Step-1: Publish Artifacts to Pipeline (Pipeline artifacts provide a way to share files between stages in a pipeline or between different pipelines. )
## Step-2: Install Latest Terraform (0.13.5) (Ideally not needed if we use default Ubuntu Agents)
## Step-3: Validate Terraform Manifests (terraform init, terraform validate)
stages:
- stage: TerraformValidate
  jobs:
    - job: TerraformValidateJob
      continueOnError: false

      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)'
          artifact: 'terraform'
          publishLocation: 'pipeline'

      - task: TerraformInstaller@0
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'

      - task: TerraformCLI@0
        displayName: 'check terraform version'
        inputs:
          command: version

      - task: TerraformCLI@0
        displayName: Terraform Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendType: 'azurerm'
          backendServiceArm: '$(AzureServiceConnection)'
          backendAzureRmResourceGroupName: '$(TFStateResourceGroup)'
          backendAzureRmStorageAccountName: '$(TFStateStorageAccount)'
          backendAzureRmContainerName: '$(TFStateStorageAccountContainer)'
          backendAzureRmKey: 'aks.terraform.tfstate'
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: Terraform Validate
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          allowTelemetryCollection: false



# Stage-2: Deploy Stages for Dev & QA
# Deployment-1: Deploy Dev AKS Cluster
## Step-1: Define Variables for environments
## Step-2: Download SSH Secure File
## Step-3: Terraform Initialize (State Storage to store in Azure Storage Account for Dev AKS Cluster)
## Step-4: Terraform Plan (Create Plan)
## Step-5: Terraform Apply (Use the plan created in previous step)
- stage: DeployAKSClusters
  jobs:
    - deployment: DeployDevAKSCluster
      displayName: DeployDevAKSCluster
      pool:
        vmImage: 'ubuntu-latest'
      environment: $(DevEnv)      
      strategy:
        runOnce:
          deploy:
            steps:            
            - task: DownloadSecureFile@1
              displayName: Download SSH Key
              name: sshkey
              inputs:
                secureFile: '$(SSHKeyFileName)'

            - task: TerraformCLI@0
              displayName: Terraform Init
              inputs:
                command: 'init'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                backendType: 'azurerm'
                backendServiceArm: '$(AzureServiceConnection)'
                backendAzureRmResourceGroupName: '$(TFStateResourceGroup)'
                backendAzureRmStorageAccountName: '$(TFStateStorageAccount)'
                backendAzureRmContainerName: '$(TFStateStorageAccountContainer)'
                backendAzureRmKey: 'aks.$(DevEnv).terraform.tfstate'
                allowTelemetryCollection: false

            - task: TerraformCLI@0
              displayName: Terraform Plan
              inputs:
                command: 'plan'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                environmentServiceName: '$(AzureServiceConnection)'
                commandOptions: '-var ssh_public_key=$(sshkey.secureFilePath) -var environment=$(DevEnv) -out $(Pipeline.Workspace)/terraform/$(DevEnv)-$(Build.BuildId).out'
                allowTelemetryCollection: false

            - task: TerraformCLI@0
              displayName: Terraform Apply
              inputs:
                command: 'apply'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                environmentServiceName: '$(AzureServiceConnection)'
                commandOptions: '$(Pipeline.Workspace)/terraform/$(DevEnv)-$(Build.BuildId).out'
                allowTelemetryCollection: false



# Stage-2: Deploy Stages for Dev & QA
# Deployment-2: Deploy QA AKS Cluster
## Step-1: Download Secure File
## Step-2: Terraform Initialize (State Storage to store in Azure Storage Account)
## Step-3: Terraform Plan 
## Step-4: Terraform Apply
    - deployment: DeployQAAKSCluster
      dependsOn: DeployDevAKSCluster
      displayName: DeployQAAKSCluster
      pool:
        vmImage: 'ubuntu-latest'
      environment: $(TestEnv)      
      strategy:
        runOnce:
          deploy:
            steps:            
            - task: DownloadSecureFile@1
              displayName: Download SSH Key
              name: sshkey
              inputs:
                secureFile: '$(SSHKeyFileName)'

            - task: TerraformCLI@0
              displayName: Terraform Init
              inputs:
                command: 'init'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                backendType: 'azurerm'
                backendServiceArm: '$(AzureServiceConnection)'
                backendAzureRmResourceGroupName: '$(TFStateResourceGroup)'
                backendAzureRmStorageAccountName: '$(TFStateStorageAccount)'
                backendAzureRmContainerName: '$(TFStateStorageAccountContainer)'
                backendAzureRmKey: 'aks.$(TestEnv).terraform.tfstate'
                allowTelemetryCollection: false

            - task: TerraformCLI@0
              displayName: Terraform Plan
              inputs:
                command: 'plan'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                environmentServiceName: '$(AzureServiceConnection)'
                commandOptions: '-var ssh_public_key=$(sshkey.secureFilePath) -var environment=$(TestEnv) -out $(Pipeline.Workspace)/terraform/$(TestEnv)-$(Build.BuildId).out'
                allowTelemetryCollection: false

            - task: TerraformCLI@0
              displayName: Terraform Apply
              inputs:
                command: 'apply'
                workingDirectory: '$(Pipeline.Workspace)/terraform'
                environmentServiceName: '$(AzureServiceConnection)'
                commandOptions: '$(Pipeline.Workspace)/terraform/$(TestEnv)-$(Build.BuildId).out'
                allowTelemetryCollection: false